name: Terraform Dev CD

on:
  pull_request:
    branches: [ develop ]

jobs:
  terraform-apply:
    name: Terraform Apply to Dev
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Terraform Init (dev)
        run: terraform -chdir=terraform/env/dev init

      - name: Terraform Apply (dev)
        run: |
          terraform -chdir=terraform/env/dev apply \
            -auto-approve \
            -input=false \
            -var="access_key_id=${{ secrets.DEV_AWS_ACCESS_KEY_ID }}" \
            -var="secret_access_key=${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}" \
            -var="username=${{ secrets.DEV_RDS_USERNAME }}" \
            -var="password=${{ secrets.DEV_RDS_PASSWORD }}"
