name: Terraform Prod CD

on:
  push:
    branches:
      - main

jobs:
  terraform-apply:
    name: Terraform Apply to Prod
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Terraform Init (prod)
        run: terraform -chdir=terraform/env/prod init

      - name: Terraform Apply (prod)
        run: |
          terraform -chdir=terraform/env/prod apply \
            -auto-approve \
            -input=false \
            -var="access_key_id=${{ secrets.PROD_AWS_ACCESS_KEY_ID }}" \
            -var="secret_access_key=${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}" \
            -var="username=${{ secrets.PROD_RDS_USERNAME }}" \
            -var="password=${{ secrets.PROD_RDS_PASSWORD }}"
